@startuml
'https://plantuml.com/class-diagram

title JPA SHOP domain diagram

class 회원
class 주문
class 배송

class 주문상품
class 상품물품
class 도서
class 음반
class 영화
class 카테고리

주문 "1" -- "*" 회원
주문 "1" -- "1" 배송
주문 "1" -- "*" 주문상품

주문상품 "*" -- "1" 상품물품
카테고리 "*" -- "*" 상품물품

상품물품 <|-- 도서
상품물품 <|-- 음반
상품물품 <|-- 영화


@enduml